version: 2
jobs:
    build:
        working_directory: /go/src/github.com/ieee0824/chiya
        docker:
            - image: golang:latest
              environment:
                  GO15VENDOREXPERIMENT: 1
        steps:
            - checkout
            - run:
                name: install glide
                command: |
                    go get github.com/Masterminds/glide
                    go install github.com/Masterminds/glide
            - run:
                name: install packages
                command:
                    glide i
            - deploy:
                name: release github
                command: |
                    if [[ "${CIRCLE_BRANCH}" =~ "^release-.*" ]]; then
                        echo "hoge"
                    fi
                    echo "end"
